DROP TABLE IF EXISTS votes CASCADE;
CREATE TABLE votes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id  UUID REFERENCES users(id) ON DELETE CASCADE,
  date_id SERIAL REFERENCES dates(id) ON DELETE CASCADE,
  isAvailable BOOLEAN DEFAULT false
);
